package com.fire.adforge.engine

import com.fire.adforge.engine.sponsors.*

object SponsorEngine {
    fun registerAll() {
        // Auto-wired by Kit506
        AdGemHandler().load()
        AdGateMediaHandler().load()
        OfferToroHandler().load()
        AyetStudiosHandler().load()
        UnityAdsHandler().load()
        ironSourceHandler().load()
        AppLovinMAXHandler().load()
        ChartboostHandler().load()
        FyberHandler().load()
        TapjoyHandler().load()
        CPAleadHandler().load()
        VungleHandler().load()
        AdColonyHandler().load()
        MintegralHandler().load()
        BideaseHandler().load()
        PollfishHandler().load()
        CPXResearchHandler().load()
        TheoremReachHandler().load()
        BitLabsHandler().load()
        PeanutLabsHandler().load()
        SaySoRewardsHandler().load()
        YourSurveysHandler().load()
        OpinionCapitalHandler().load()
        AwinHandler().load()
        AdmitadHandler().load()
        CJAffiliateHandler().load()
        RakutenAdsHandler().load()
        FlexOffersHandler().load()
        ImpactComHandler().load()
        RevenueUniverseHandler().load()
        KiwiWallHandler().load()
        WannadsHandler().load()
        MonlixHandler().load()
        UserTestingHandler().load()
        RespondentIOHandler().load()
        ProlificHandler().load()
        TestableMindsHandler().load()
        TolunaHandler().load()
        MindswarmsHandler().load()
        RevLifterHandler().load()
        RakutenHandler().load()
        HoneyRewardsHandler().load()
        SlickdealsHandler().load()
        RetailMeNotHandler().load()
        RewardZoneHandler().load()
        FlashRewardsHandler().load()
        ShoppersVoiceHandler().load()
        PrizeRebelHandler().load()
        InboxDollarsHandler().load()
        GrabPointsHandler().load()
        MoPubLegacyHandler().load()
        ChartboostMediationHandler().load()
    }
}
